### PR TITLE
Update ping.js

### PR DESCRIPTION
**Pull request by aleksanderxh**
Since Self-Hosting is a thing, it should be the client's username

### CODE REVIEW

**Comment by SunburntRock89** [comment]
No, it should be allowed.

**Comment by TheRandomMelon** [comment]
Yeah I have no idea what you mean by "Yeah it should be allowed." @SunburntRock89

**Comment by mrdnomaid** [comment]
Perhaps rename it to "Melonian Core" or something, like @JakeMakesStuff does with Cube

**Comment by TheRandomMelon** [comment]
Melonian Core? What?

**Comment by SonicHack2** [comment]
whats a sunburnt rock meant to be anyway ha

**Comment by mrdnomaid** [comment]
@TheRandomMelon I mean in the footer for non-official instances. I just think "using Melonian" sounds strange.

**Comment by TheRandomMelon** [comment]
So, what would we say?

**Comment by mrdnomaid** [comment]
@TheRandomMelon "JamesB#007 using Melonian Core 52.07.beta.alpha.2111" maybe

**Comment by SunburntRock89** [comment]
Wait, I understand now, yeah, this could be merged

**Comment by aleksanderxh** [comment]
Perhaps, it can be something like "BotUsername vVERSION-HERE powered by Melonian"

**Comment by mrdnomaid** [comment]
"powered by" makes a lot more sense than our suggestions; I'd go with that.

**Comment by TheRandomMelon** [comment]
Cool. I'll merge now.

**Pull request merged**
