### PR TITLE
❌ Implement Error Catching

### PR DESCRIPTION
**Pull request by aleksanderxh**
THE BOT SHALL NOT CRASH

### CODE REVIEW

**Comment by SunburntRock89** [comment]
Note: Don't export config, just rerequire it

**Comment by aleksanderxh** [comment]
@TheRandomMelon Can you purposefully break a command and test this?

**Comment by SunburntRock89** [comment]
@aleksanderxh if you're gonna be a developer, you have to test yourself

**Comment by aleksanderxh** [comment]
@SunburntRock89 I fucking can't. I'm not at home over at my PC where I can test.

**Comment by SunburntRock89** [comment]
I'll dismiss them if they haven't been thought through properly

**Comment by SunburntRock89** [comment]
Also, you didn't lint it properly!!!!

**Comment by SunburntRock89** [comment]
for fuck sake, is it that hard @TheRandomMelon

**Comment by SunburntRock89** [comment]
Lmao, controlling, literally just telling you that you didn't lint the embed

**Comment by TheRandomMelon** [comment]
image
uh huh

**Comment by SunburntRock89** [comment]
I had a reason to dismiss it

**Comment by TheRandomMelon** [comment]
"Requested Changes"

**Comment by TheRandomMelon** [comment]
Listen, let's take this to Discord DMs. No need to flood this with more drama.

**Pull request closed without merging**
